{% set name = "itk" %}
{% set version = "5.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 1
  skip: True  # [py2k or win32]

requirements:
  build:
    - python
    - pip
    - wheel
  run:
    - python
    - numpy

test:
  imports:
    - itk

about:
  home: https://www.itk.org/
  license: Apache-2.0
  license_file: 
    - LICENSE.txt
    - NOTICE
  summary: ITK is an open-source toolkit for multidimensional image analysis
  doc_url: https://itk.org/ITK/help/documentation.html
  dev_url: https://github.com/InsightSoftwareConsortium/ITK
